version: '3.8'

services:
  neo4j:
    image: neo4j:5.14.0
    container_name: memos-neo4j
    ports:
      - "0.0.0.0:7474:7474"  # Web interface
      - "0.0.0.0:7687:7687"  # Bolt protocol
    environment:
      - NEO4J_AUTH=neo4j/memospassword123
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms_memory_heap_initial__size=1G
      - NEO4J_dbms_memory_heap_max__size=2G
    volumes:
      - ./data/neo4j:/data
      - ./logs/neo4j:/logs
    networks:
      - memos-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "neo4j", "status"]
      interval: 30s
      timeout: 10s
      retries: 3

  qdrant:
    # image: qdrant/qdrant:v1.7.4

    # Qdrant client version 1.14.3 is incompatible with server version 1.7.4. Major versions 
    # should match and minor version difference must not exceed 1. Set check_compatibility=False 
    # to skip version check.
    image: qdrant/qdrant:v1.14.3
    
    container_name: memos-qdrant
    ports:
      - "0.0.0.0:6333:6333"  # REST API
      - "0.0.0.0:6334:6334"  # gRPC
    volumes:
      - ./data/qdrant:/qdrant/storage
    networks:
      - memos-network
    restart: unless-stopped

  # Text Embeddings Inference (CPU)
  tei:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.8.1
    container_name: memos-tei
    # Expose to host if you want to cURL from the host. If only internal use is needed, you can remove this.
    ports:
      - "0.0.0.0:8080:80"
    # Choose your model here; `all-mpnet-base-v2` is a solid general choice (768 dims).
    command: ["--model-id", "sentence-transformers/all-mpnet-base-v2"]
    environment:
      # Optional, speeds up downloads a bit
      - HF_HUB_ENABLE_HF_TRANSFER=1
      # If you need private/gated models, uncomment and put your token:
      # - HF_TOKEN=hf_xxx
    volumes:
      # Persist model + tokenizer downloads
      - ./data/hf-cache:/data
    networks: [memos-network]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost/health"]
      interval: 15s
      timeout: 5s
      retries: 20

  memos-api:
    build:
      context: ..
      dockerfile: docker-dev/Dockerfile
    container_name: memos-api-dev
    ports:
      - "0.0.0.0:8000:8000"  # API
      - "0.0.0.0:5678:5678"  # Debugpy
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUGPY_ENABLE=true
    volumes:
      # Mount source code for live reload - using actual MemOS structure
      - ../src:/app/src:rw
      - ./debug_scripts:/app/debug_scripts:ro
      - ./data/memos:/app/data:rw
      - ./logs/memos:/app/logs:rw
      # Mount examples and test data if needed
      - ../examples:/app/examples:ro
      - ../tests:/app/tests:ro
    depends_on:
      - neo4j
      - qdrant
      - tei
    networks:
      - memos-network
    restart: unless-stopped
    stdin_open: true
    tty: true

networks:
  memos-network:
    driver: bridge
